title: Davide Talon
position: PhD Student
affiliation: Italian Institute of Technology
email: davide dot talon at iit dot it
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=IiMwp7EAAAAJ&hl=it
github_link: https://github.com/davidetalon
linkedin: https://www.linkedin.com/in/davidetalon
avatar: ./assets/img/profile-informal-square.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Here davide talon's personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
url: https://davidetalon.github.io/